#!/bin/sh
#python bayes_opt_fbk.py --dynet-autobatch 1 -d data -m models/model -t ATIS --task slot_filling -wv glove.6B.300d.txt -b random most-similar-examples -f similarity diversity --feature-weights-file logs/CONLL_2003_NER_ATIS.weight  --z-norm --num-iterations 5  --num-runs 1 --log-file logs/log -s CONLL_2003_NER --mtl-target ATIS --mtl-aux CONLL_2003_NER --mtl-root-result /home/ubuntu/sandbox/learn-to-select-data/mtl_result --mtl-directory-name  MTL_CONLL_FILTERED_ATIS_400 --mtl-epoch 50 --mtl-nb-sentence 400 --mtl-batch-range max

#python bayes_opt_fbk.py --dynet-autobatch 1 -d data -m models/model -t ATIS --task slot_filling -wv glove.6B.300d.txt -b random most-similar-examples -f similarity diversity --feature-weights-file logs/CONLL_2003_NER_ATIS.weight  --z-norm --num-iterations 5  --num-runs 1 --log-file logs/log -s CONLL_2003_NER --mtl-target ATIS --mtl-aux CONLL_2003_NER --mtl-root-result /home/ubuntu/sandbox/learn-to-select-data/mtl_result --mtl-directory-name  MTL_CONLL_FILTERED_ATIS_800 --mtl-epoch 50 --mtl-nb-sentence 800 --mtl-batch-range max

python bayes_opt_fbk.py --dynet-autobatch 1 -d data -m models/model -t MIT_Restaurant --task slot_filling -wv glove.6B.300d.txt -b random most-similar-examples -f similarity diversity --feature-weights-file logs/CONLL_2003_NER_MIT_Restaurant.weight  --z-norm --num-iterations 5  --num-runs 1 --log-file logs/log -s CONLL_2003_NER --mtl-target MIT_Restaurant --mtl-aux CONLL_2003_NER --mtl-root-result /home/ubuntu/sandbox/learn-to-select-data/mtl_result --mtl-directory-name  MTL_CONLL_FILTERED_MIT_Restaurant_200 --mtl-epoch 50 --mtl-nb-sentence 200 --mtl-batch-range max
wait
python bayes_opt_fbk.py --dynet-autobatch 1 -d data -m models/model -t MIT_Restaurant --task slot_filling -wv glove.6B.300d.txt -b random most-similar-examples -f similarity diversity --feature-weights-file logs/CONLL_2003_NER_MIT_Restaurant.weight  --z-norm --num-iterations 5  --num-runs 1 --log-file logs/log -s CONLL_2003_NER --mtl-target MIT_Restaurant --mtl-aux CONLL_2003_NER --mtl-root-result /home/ubuntu/sandbox/learn-to-select-data/mtl_result --mtl-directory-name  MTL_CONLL_FILTERED_MIT_Restaurant_400 --mtl-epoch 50 --mtl-nb-sentence 400 --mtl-batch-range max
wait
python bayes_opt_fbk.py --dynet-autobatch 1 -d data -m models/model -t MIT_Restaurant --task slot_filling -wv glove.6B.300d.txt -b random most-similar-examples -f similarity diversity --feature-weights-file logs/CONLL_2003_NER_MIT_Restaurant.weight  --z-norm --num-iterations 5  --num-runs 1 --log-file logs/log -s CONLL_2003_NER --mtl-target MIT_Restaurant --mtl-aux CONLL_2003_NER --mtl-root-result /home/ubuntu/sandbox/learn-to-select-data/mtl_result --mtl-directory-name  MTL_CONLL_FILTERED_MIT_Restaurant_800 --mtl-epoch 50 --mtl-nb-sentence 800 --mtl-batch-range max
wait
python bayes_opt_fbk.py --dynet-autobatch 1 -d data -m models/model -t MIT_Movie --task slot_filling -wv glove.6B.300d.txt -b random most-similar-examples -f similarity diversity --feature-weights-file logs/CONLL_2003_NER_MIT_Movie.weight  --z-norm --num-iterations 5  --num-runs 1 --log-file logs/log -s CONLL_2003_NER --mtl-target MIT_Movie --mtl-aux CONLL_2003_NER --mtl-root-result /home/ubuntu/sandbox/learn-to-select-data/mtl_result --mtl-directory-name  MTL_CONLL_FILTERED_MIT_Movie_200 --mtl-epoch 50 --mtl-nb-sentence 200 --mtl-batch-range max
wait
python bayes_opt_fbk.py --dynet-autobatch 1 -d data -m models/model -t MIT_Movie --task slot_filling -wv glove.6B.300d.txt -b random most-similar-examples -f similarity diversity --feature-weights-file logs/CONLL_2003_NER_MIT_Movie.weight  --z-norm --num-iterations 5  --num-runs 1 --log-file logs/log -s CONLL_2003_NER --mtl-target MIT_Movie --mtl-aux CONLL_2003_NER --mtl-root-result /home/ubuntu/sandbox/learn-to-select-data/mtl_result --mtl-directory-name  MTL_CONLL_FILTERED_MIT_Movie_400 --mtl-epoch 50 --mtl-nb-sentence 400 --mtl-batch-range max
wait
python bayes_opt_fbk.py --dynet-autobatch 1 -d data -m models/model -t MIT_Movie --task slot_filling -wv glove.6B.300d.txt -b random most-similar-examples -f similarity diversity --feature-weights-file logs/CONLL_2003_NER_MIT_Movie.weight  --z-norm --num-iterations 5  --num-runs 1 --log-file logs/log -s CONLL_2003_NER --mtl-target MIT_Movie --mtl-aux CONLL_2003_NER --mtl-root-result /home/ubuntu/sandbox/learn-to-select-data/mtl_result --mtl-directory-name  MTL_CONLL_FILTERED_MIT_Movie_800 --mtl-epoch 50 --mtl-nb-sentence 800 --mtl-batch-range max